---
title: "Lecture 2"
date: today
format: html
---

## IRB update?
是否提交你的IRB？老师那边是否有任何回应？

## Interview Themes

五个方面关于在英国的体验（包容度，安全，经济情况），3个问题future plan.

要不要限定一下你的采访对象（screening criteria):

- 必须是中国学生，
- 他们要有读研究生的打算
- UK vs. Singapore, Hongkong and Mainland China (Chinese culture which offers postgraduate Course taught in English)

### Academic and Career Factor
- What are differences between UK and Asian educational system?
- What aspects of the UK/Asian education system are attracting you to pursue a master’s degree here?
- Do you believe that the academic achievement in the UK/Asia will influence your career destination, why?
- (if so, do you think this master degree will boost the chance of getting a job here)?
- (if not, why you still choose a place that is not consistent with your career destination)?

### Security Concern Factor
- Are there any special safety concerns facilitate your choice to study in one place over another?
- Do the security management on campus can override your concern of the safety issues in the society?
- Do you have higher sense of safety security in your home country rather than the UK？
- Have you expereinced any safety issues when you were studying in the UK?
- (If so,) Do you believe this experience determine your final choice in postgraduate school?
- (if not,) Why this does not prevent you from determining to study here?

### Financial Factor
- What are the financial aspect(transportation, rental issues, tuition fee and exchange rate) in your decision to pursue a master's degree in the UK versus Asia?
- Have you compared the tuition fees and living expenses between the UK and - Asian countries? What are your findings?
- Are scholarships or financial aid opportunities influencing your choice of location for postgraduate studies?
- Does the potential return (successful rate of gaining the degree, job opportunity after graduation and whether the future salary can offset the cost of pursuing this degree)on investment from a UK master's degree justify the higher costs for you? Why or why not?

### Cultural and Social Factor
- Are cultural or social factors in either the UK or Asia pushing you away from studying there? (if students confess some issues in Asia, you might ask whether it is the study pressure)
- Have you experienced any racism in the UK?
- (If so) Will this influence your final decsion to stay or go to Asia, why?
- Have you gained a sense of integration in the UK?
-- (If so) does this affect your decision to stay? --(if not) does integration influence your decision to go back to Asia?
- Are global events (e.g., political climate, pandemics) acting as push or pull factors in your decision? Why?






